#Interpret modeling results
#Use this code to load the modeling results generated by `modelComparisonCV.R` and save them to disk on lines 124 and 125 to be read in by modelResultsNotebook.Rmd
#Charley Wu, Jan 2020

#house keeping
rm(list=ls())

#load packages
packages <- c("coin", 'ggbeeswarm', 'pander', 'lsr','cowplot', 'BayesFactor', 'readr', 'plyr', 'jsonlite', 'ggplot2', 'scales', "ggExtra", 'gridExtra', 'reshape2', 'stargazer', 'coefplot', "grid", 'corrplot', 'ggsignif')
lapply(packages, require, character.only = TRUE)

source("dataProcessing.R")
#source("multiplot.R")
source('statisticalTests.R')

theme_set(theme_cowplot(font_size=12))
#############################################################################################################################
# IMPORT PARTICIPANT DATA 
#############################################################################################################################
#Participant data
data<-dataImport(normalize = F)
#remove null rows
#data <- na.omit(data)
uids <- unique(data$id)

#############################################################################################################################
# IMPORT MODELING RESULTS
#############################################################################################################################

importModelResults <- function(dataFolder, kernels, acqFuncs){
  #initialize data frames
  modelFit <- data.frame() 
  paramEstimates <- data.frame()
  choicePredictions <- data.frame(participant=numeric(), environment=numeric(), context = character(), round=numeric(), trial = numeric(), choice=numeric(),  kernel=numeric(), acq=numeric(), nLL=numeric())
  #loop through data
  for (context in c("Conceptual", "Spatial")){
    for (k in kernels){
      for (a in acqFuncs){
        for (i in uids){ #subjects
          filename <- paste0(dataFolder,context,".", k, a, i, ".Rdata") #read output file
          if (file.exists(filename)){
            #debug: 
            #filename <- 'modelResults/batch5/Conceptual.RBFUCB10.Rdata'
            #k <- 'RBF'
            #a <- 'UCB'
            #i <- 10
            #context <- 'Conceptual'
            datalist<-get(load(filename))
            dp <- datalist[[1]] #MLE
            smlist <- datalist[[2]] #Softmax prediction surface
            choiceHistory <- datalist[[3]] #choices
            #demographics
            dummy<-subset(data, id==i) #subset participant in the dataframe
            environment <- dummy$environment[1]
            participant<-dummy$id[1]  #replicate ID
            kernel<-k
            acq<-a
            #Total out of sample nLL
            nLL <- sum(dp$nLL)
            randomModelLL <- -log(1/64)*171
            R2 <- 1 - (nLL/randomModelLL)
            #save modelFit
            dadd<-data.frame(participant=participant, environment=environment, context = context, nLL=nLL, kernel=kernel, acq = acq, R2 =R2, kError = median(dp$errorVariance), lambda=median(dp$lambda), beta = median(dp$beta), tau=median(dp$tau), p = median(dp$p))
            modelFit<-rbind(modelFit, dadd)
            # save all 8 parameter estimates for each subject
            dadd<-data.frame(participant=participant, environment=environment,context = context, leaveoutindex =dp$loo, nLL=sum(dp$nLL), R2 =R2,  kernel=kernel, acq = acq, kError = dp$errorVariance, lambda=dp$lambda, beta=dp$beta,  tau=dp$tau, p = dp$p, roundnLL=dp$nLL)
            paramEstimates<-rbind(paramEstimates, dadd)
            #Save log loss for individual choices
            individualChoices <- sapply(1:9, FUN= function(r){  #loop through rounds
              roundM <- smlist[[r]] #choice matrix for round r
              choices <- cbind(1:19, choiceHistory[r,1:19]) #join into two column matrix: trial number, choice selection
              nLL <- - log(roundM[choices]) #compute log loss for each individual choice
            } ) #returns trial x round matrix of log loss values for each individual choice
            choiceVector <- as.vector(individualChoices) #unravel into vector
            roundVec <- rep(seq(1,9), each=19)
            trialVec <- rep(seq(1,19), 9)
            dummyDF <- data.frame(participant=participant, environment=environment, context = context, round= roundVec, trial = trialVec, choice = as.vector(choiceHistory[,1:19]),  kernel=kernel, acq = acq, nLL = choiceVector)
            choicePredictions <- rbind(choicePredictions, dummyDF)
            
          }}}}}
  return(list(modelFit, paramEstimates, choicePredictions))
}

#############################################################################################################################
# COMPILE MODELING RESULTS
#
#############################################################################################################################
#modelList <- c("BMT",  "RBF", 'SimKernel')
modelList <- c("BMT",  "RBF", 'SimKernel')
acqusitionFuncs<-  c("UCB")

modelResults <- importModelResults('modelResults/batch5/', modelList, acqusitionFuncs)

#separate into overall per participant and individual cross validation blocks
modelFit <- modelResults[[1]]
paramEstimates <- modelResults[[2]]
choicePredictions <- modelResults[[3]]

#reorder acqisition function levels and add "ModelName" to identify unique models
modelFit$acq <-factor(modelFit$acq)
modelFit$kernel <- factor(modelFit$kernel)
#levels(modelFit$kernel) <- c("BMT", "RBF")
modelFit$ModelName <- paste(modelFit$kernel,modelFit$acq, sep = "-")
modelFit$ModelName <- factor(modelFit$ModelName)

paramEstimates$kernel <- factor(paramEstimates$kernel)
#levels(paramEstimates$kernel) <- c("BMT", "RBF")

#add participant data to modelFit
meanDF <- ddply(data, .(id, context, environment, contextOrder), plyr::summarize, meanScore = mean(z))
modelFit <- merge(modelFit, meanDF, by.x=c("participant","context", "environment"), by.y=c("id", "context", "environment"))

modelFit$contextOrder <- factor(modelFit$contextOrder)
levels(modelFit$contextOrder)<- c("Spatial First", "Conceptual First")


#add participant data to paramEstimates
paramEstimates <- merge(paramEstimates, meanDF, by.x=c("participant","context", "environment"), by.y=c("id", "context", "environment"))
paramEstimates$contextOrder <- factor(paramEstimates$contextOrder)
levels(paramEstimates$contextOrder)<- c("Spatial First", "Conceptual First")

#SAVE MODEL RESULTS TO DISK
#write.csv(modelFit,'modelResults/modelFit.csv')
#write.csv(paramEstimates,'modelResults/paramEstimates.csv')


# Load all models so far:
#modelFit <- read.csv('modelResults/modelFit.csv')
#paramEstimates <- read.csv('modelResults/paramEstimates.csv')


#############################################################################################################################
# SAVE PARAMETER ESTIMATES FOR RATIONAL MODELS
#############################################################################################################################

#BMTpars <- subset(paramEstimates, kernel=="BMT" & acq=="UCB")
#write.csv(BMTpars[,c("participant", "leaveoutindex", "environment","context","kError", "beta", "tau")], file = "rationalModels/parameters/BMT.csv", row.names = FALSE)

#GPpars <- subset(paramEstimates, kernel=="RBF" & acq=="UCB")
#write.csv(GPpars[,c("participant", "leaveoutindex", "environment","context","lambda", "beta", "tau")], file = "rationalModels/parameters/gpucb.csv", row.names = FALSE)

#SimKernelPars <- subset(paramEstimates, kernel=="SimKernel" & acq=="UCB")
#write.csv(SimKernelPars[,c("participant", "leaveoutindex", "environment","context","lambda", "beta", "p", "tau")], file = "rationalModels/parameters/simKernelucb.csv", row.names = FALSE)

#############################################################################################################################
# Summary of Modeling Results
#############################################################################################################################


#Number of participants best described
modelFit$bestFit <- 0
for (contextType in c("Conceptual", "Spatial")){
  models <-  rep(0, length(levels(modelFit$ModelName)))
  names(models) <- levels(modelFit$ModelName)
  for (pid in uids){
    subDF <- subset(modelFit, participant==pid & context==contextType)
    best <- subDF$ModelName[which(subDF$R2==max(subDF$R2))]
    modelFit[modelFit$participant==pid & modelFit$context==contextType & modelFit$ModelName==best,'bestFit'] <- 1
    models[best] <- models[best] + 1
  }
  #add best described to modelFit 
  bestDescribed <- paste0('bestDescribed', contextType)
  modelFit[bestDescribed] <- NA
  for (mod in names(models)){
    modelFit[modelFit$ModelName == mod,bestDescribed] <- models[mod]
  }
  #Summary of results
  cat(paste0(contextType, " Task", "\n"))
  for (k in levels(modelFit$kernel)){
    for (a in levels(modelFit$acq)){
      if (paste(k,a,sep="-") %in% names(models)){
        sub <- subset(modelFit, acq == a & kernel == k & context==contextType) #sub of model fit
        psub <- subset(paramEstimates, acq == a & kernel==k & context==contextType)
        randomModel <- -log(1/64) * 19*9
        r_2 <- 1 - (mean(sub$nLL)/randomModel)
        bestDescribed <- models[paste(k,a,sep="-")]
        cat( k,"-",a, " (n=",nrow(sub),")", "; R2 = ", round(r_2, digits=2),"; Best Described = ", bestDescribed , "; Lambda = ", round(median(psub$lambda), digits=2),"; Beta = ", round(median(psub$beta), digits=2), "; kError = ", round(median(psub$kError), digits=2), "; Tau = ", round(median(psub$tau), digits=2),  "; p = ", round(median(psub$p), digits=2), "\n", sep="")
      }
    }
  }
  cat("\n")
}

modelFit$bestFit <- factor(modelFit$bestFit)
#############################################################################################################################
# Summary of Modeling Results
#############################################################################################################################
#Which models to include?
modelList <- c('RBF', 'BMT')
modelFit <- subset(modelFit, kernel %in% modelList)

#Model comparison
ttestPretty(subset(modelFit, context =='Conceptual' & ModelName == 'RBF-UCB')$R2, subset(modelFit, context =='Conceptual' & ModelName == 'BMT-UCB')$R2, paired = T)
ttestPretty(subset(modelFit, context =='Spatial' & ModelName == 'RBF-UCB')$R2, subset(modelFit, context =='Spatial' & ModelName == 'BMT-UCB')$R2, paired = T)

#Model comparison
modelFit$kernel <- factor(modelFit$kernel, levels=c('RBF', 'BMT'))
levels(modelFit$kernel) <- c('GP', 'BMT')
contextLabels <- c("Conceptual"="Conceptual Task", "Spatial"="Spatial Task")
p1 <- ggplot(modelFit, aes(x = kernel, y = R2, color = kernel))+
  geom_line(aes(group=participant), color = 'black', alpha = 0.1)+
  geom_boxplot(outlier.shape=NA, width = .2, fill = NA, color = 'black')+
  geom_quasirandom(alpha = 0.7)+
  stat_summary(fun.y=mean, geom='point', color = 'black', shape = 5, size = 2)+
  #stat_summary(fun.data=mean_cl_boot, geom='errorbar', width = .2, color = 'black')+
  facet_grid(~context, labeller=as_labeller(contextLabels)) +
  #theme_classic()+
  ylab('Predictive Accuracy')+
  xlab('')+
  #scale_color_manual(values = c("#e6ab02","#a6761d", "#7570b3"), name='')+
  scale_color_manual(values = c("#e6ab02", "#7570b3"), name='')+
  theme(legend.position="none", strip.background=element_blank(), legend.key=element_rect(color=NA))
p1      


#context order effect
ttestPretty(subset(modelFit, context == "Conceptual" & contextOrder=="Spatial First")$R2, subset(modelFit,  context == "Conceptual" & contextOrder=="Conceptual First")$R2)

#Calculate PXP
#Save nLLs as csv
#Just RBF and BMT
write.table(cbind(subset(modelFit, context =='Conceptual' & ModelName == 'RBF-UCB')$nLL, subset(modelFit, context =='Conceptual' & ModelName == 'BMT-UCB')$nLL), 'modelResults/conceptualdiffevidence.csv', row.names = FALSE, sep=',', col.names=FALSE)
write.table(cbind(subset(modelFit, context =='Spatial' & ModelName == 'RBF-UCB')$nLL, subset(modelFit, context =='Spatial' & ModelName == 'BMT-UCB')$nLL), 'modelResults/spatialdiffevidence.csv', row.names = FALSE, sep=',',col.names=FALSE)

#Intermediate step: run pxp.m

#build dataframe with output
pxpDF <- data.frame(model= rep(c('GP', 'BMT'),2), context = c('Conceptual', 'Conceptual', 'Spatial','Spatial' ), pxp= c(0.997038914713137,	0.00296108528686250,0.999995902345119,	4.09765488129429e-06))
#Reorder levels
pxpDF$model <- factor(pxpDF$model , levels=c('GP', 'BMT'))


p2 <- ggplot(pxpDF, aes(x = model, y = pxp, fill = model))+
  geom_bar(stat="identity",color='black')+
  facet_grid(~context,labeller=as_labeller(contextLabels))+
  ylab('PXP')+
  xlab('')+
  scale_y_continuous(labels = percent)+
  expand_limits(y=0)+
  #scale_fill_manual(values = c("#e6ab02","#a6761d", "#7570b3"), name='')+
  scale_fill_manual(values = c("#e6ab02","#7570b3"), name='')+
  theme(legend.position="none", strip.background=element_blank(), legend.key=element_rect(color=NA))
p2
#############################################################################################################################
#Simulated learning curves
#From modelSimulations.R
#############################################################################################################################
# # Load all models
randomDF <- read.csv("rationalModels/random.csv")
bmtDF <- read.csv("rationalModels/BMTUCB.csv")
gpDF <- read.csv("rationalModels/GPUCB.csv")


#Join all DFs together 
rationalDF <- rbind(randomDF, bmtDF, gpDF)
rationalDF$Environment <- factor(rationalDF$Environment, levels=c("Rough", "Smooth"))
rationalDF <- rationalDF[ , !(names(rationalDF) %in% c("X"))]

dplot<-ddply(data,~trial+environment+context,summarise,meanReward=mean(z), meanSE=se(z))
colnames(dplot)[2]<-"Environment" #rename colname
colnames(dplot)[3] <- "Context"
dplot$Model <- rep("Human", nrow(dplot))
#Join human with rational models
rationalDF <- rbind(rationalDF, dplot)

summary(rationalDF)
#rationalDF$trial <- rationalDF$trial - 1

#reorder factor levels
rationalDF$Model <- factor(rationalDF$Model, levels = c("Random",  "GP-UCB", "BMT-UCB" , "Human"))
levels(rationalDF$Model) <- c("Random",  "GP",  "BMT" , "Human")
#Plot of mean Reward
taskEnvLabels <- c("Conceptual"="Conceptual Task", "Spatial"="Spatial Task", "Rough"="Rough", "Smooth"= "Smooth")
p3<- ggplot(rationalDF, aes(x=trial, y=meanReward, col=Model, shape=Model))+
  stat_summary(fun.y = mean, geom='line', size = 0.8)+
  #stat_summary(fun.y=mean, geom='point', size = 2)+
  #geom_point(size=2) +
  #geom_line(size=.8) +
  #geom_errorbar(aes(ymin=meanReward-meanSE, ymax=meanReward+meanSE), width=0.1, size=1) +
  ylab("Average Reward")+xlab("Trial")+
  theme_classic()+
  facet_grid(Environment~ Context, labeller=as_labeller(taskEnvLabels)) +
  scale_shape_manual(values = c(32, 16,17,15,4,7)) +
  #scale_color_manual(values=c("black","#7570B3", "#1B9E77", "#fb9a99"))+
  scale_color_manual(values=c("black","#e6ab02", "#7570b3","#fb9a99"))+
  #scale_linetype_manual(values = c('solid', 'dotted', 'solid', 'dotted', 'solid', 'solid'))+
  #scale_color_brewer(palette="Paired", direction=1)+
  #coord_cartesian(ylim=c(45,85))+
  scale_x_continuous(breaks = round(seq(0,20, by = 5),1))+
  theme(legend.position="right", strip.background=element_blank(), legend.key=element_rect(color=NA))
p3
#ggsave(filename = "plots/modelPerformanceAvg.pdf", plot = p1,height = 3.5, width = 9, units = "in", useDingbats=FALSE) 


###########################################################################################################################
#Parameter Correlation - GP-UCB
###########################################################################################################################
source('statisticalTests.R')

#GP-UCB
k<- 'RBF'
a<- "UCB"
conceptualDF<- subset(paramEstimates, kernel==k & acq==a & context=="Conceptual")
conceptualParams <- ddply(conceptualDF, ~participant+environment+contextOrder, plyr::summarize, Conceptuallambda=mean(lambda), Conceptualbeta = mean(beta), Conceptualtau = mean(tau))

gridDF<- subset(paramEstimates, kernel==k & acq==a & context == "Spatial")
gridParams <- ddply(gridDF, ~participant+environment+contextOrder, plyr::summarize, Spatiallambda=mean(lambda), Spatialbeta = mean(beta), Spatialtau = mean(tau))

corDF <- merge(conceptualParams, gridParams, by=c("participant", "environment", "contextOrder"))
corDF$environment <- factor(corDF$environment, levels=c("Rough", "Smooth"))

#Lambda 
corTestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda, method ='kendall') #$r_{\tau}=.13$, $p=.028$, $BF=1.3$
ttestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda, var.equal=T, paired=T) #$t(128)=2.2$, $p=.028$, $d=0.3$, $BF=1.0$
#ranktestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda, paired=T) #$Z=-1.2$, $p=.115$, $r=-.11$, $BF=.13$
#Beta#
corTestPretty(conceptualParams$Conceptualbeta, gridParams$Spatialbeta, method ='kendall') #$r_{\tau}=.18$, $p=.002$, $BF=13$
ttestPretty(conceptualParams$Conceptualbeta, gridParams$Spatialbeta,var.equal=T, paired=T) #$t(128)=1.3$, $p=.181$, $d=0.09$, $BF=.24$
#ranktestPretty(conceptualParams$Conceptualbeta, gridParams$Spatialbeta, paired=T) # $Z=-5.0$, $p<.001$, $r=-.44$, $BF>100$
#Tau
corTestPretty(conceptualParams$Conceptualtau, gridParams$Spatialtau, method ='kendall') #$r_{\tau}=.43$, $p<.001$, $BF>100$x
ttestPretty(conceptualParams$Conceptualtau, gridParams$Spatialtau,var.equal=T, paired=T) #$t(128)=1.1$, $p=.271$, $d=0.08$, $BF=.18$
#ranktestPretty(conceptualParams$Conceptualtau, gridParams$Spatialtau, paired=T) #$Z=-6.9$, $p<.001$, $r=-.61$, $BF=NA$

#LAMBDA 
#Max axis value
uppertquartiles <- c(quantile(corDF$Conceptuallambda, probs=c(.25, .75))[2], quantile(corDF$Spatiallambda, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptuallambda, na.rm = T), 1.5 * IQR(corDF$Spatiallambda, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits
#Density for plotting
corDF$lambdadensity <- fields::interp.surface(MASS::kde2d(conceptualParams$Conceptuallambda, gridParams$Spatiallambda), corDF[,c("Conceptuallambda", "Spatiallambda")]) #bivariate point density

lambdaCor <- "paste(r[tau], \" = .13\",  ~~italic(p), \" = .028\")"
p4a <- ggplot(subset(corDF,Conceptuallambda <= upperLimit &  Spatiallambda<= upperLimit), aes(Conceptuallambda, Spatiallambda)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment
  #geom_smooth(method='lm', color='black', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  xlab(expression("Conceptual "*lambda))+
  ylab(expression("Spatial "*lambda)) +
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  #annotate("text", x = 1, y = 2.4, label = lambdaCor, parse=TRUE, size=4,  family="sans") +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  theme(text = element_text(size=16,  family="sans"))+
  #ggtitle('Parameter correlations')+
  theme(title = element_text(family = 'sans'), legend.position='none', 
        legend.background = element_rect(fill='transparent'))
p4a <- ggExtra::ggMarginal(p4a, type = "boxplot", fill='transparent', size = 10, outlier.shape = NA) #add marginal boxplots
p4a
#ggsave(filename = 'plots/lambda.pdf', p2a, height =3, width = 3, units = "in")

#BETA
corTestPretty(corDF$Conceptualbeta, corDF$Spatialbeta, method = 'kendall') #correlation test
#ranktestPretty(corDF$Conceptualbeta, corDF$Spatialbeta, paired=T) # "$Z=-5.1$, $p<.001$, $r=-.46$, $BF>100$"
#differences across environments
#ranktestPretty(c(subset(corDF, environment=="Rough")$Conceptualbeta, subset(corDF, environment=="Rough")$Spatialbeta), c(subset(corDF, environment=="Smooth")$Conceptualbeta, subset(corDF, environment=="Smooth")$Spatialbeta), paired=F) #$U=3780$, $p=.061$, $r_{\tau}=-.11$, $BF=.79$
#Spatial only
#ranktestPretty(subset(corDF, environment=="Rough")$Spatialbeta, subset(corDF, environment=="Smooth")$Spatialbeta, paired=F) #$U=737$, $p=.004$, $r_{\tau}=-.24$, $BF=2.4$

#Density and upper limits
corDF$betadensity <- fields::interp.surface(MASS::kde2d(corDF$Conceptualbeta, corDF$Spatialbeta), corDF[,c("Conceptualbeta", "Spatialbeta")]) #bivariate point density
uppertquartiles <- c(quantile(corDF$Conceptualbeta, probs=c(.25, .75))[2], quantile(corDF$Spatialbeta, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptualbeta, na.rm = T), 1.5 * IQR(corDF$Spatialbeta, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits


betaCor <- "paste(r[tau], \" = .18\",  ~~italic(p), \" = .002\")"
p4b <- ggplot(subset(corDF, Conceptualbeta<=upperLimit & Spatialbeta<=upperLimit), aes(Conceptualbeta, Spatialbeta)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(method='lm',color='black', se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  scale_x_continuous(limits=c(0,upperLimit), breaks= scales::pretty_breaks(n = 5)) +
  scale_y_continuous(limits=c(0,upperLimit), breaks= scales::pretty_breaks(n = 5)) +
  xlab(expression("Conceptual "*beta))+
  ylab(expression("Spatial "*beta)) +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  #annotate("text", x = 0.15, y = 0.33, label =betaCor, parse=TRUE, size=4,  family="sans")+
  theme(text = element_text(size=16,  family="sans"))+
  theme(title = element_text(family = 'sans'), legend.position="None")
p4b <- ggExtra::ggMarginal(p4b, type = "boxplot", fill='transparent', size=10)
p4b

#ggsave(filename = 'plots/beta.pdf', p2b, height =3, width = 3, units = "in")

#TAU
corTestPretty(corDF$Conceptualtau, corDF$Spatialtau, method = 'kendall') #correlation test "$r_{\tau}=.43$, $p<.001$, $BF>100$"
ttestPretty(corDF$Conceptualtau, corDF$Spatialtau, var.equal = TRUE, paired=T) #"$t(128)=1.1$, $p=.271$, $d=0.08$, $BF=.18$"

#Wilcoxon signed rank test
#ranktestPretty(corDF$Conceptualtau, corDF$Spatialtau, paired=T) #$Z=-6.9$, $p<.001$, $r=-.61$, $BF>100"

#Density and upper limits
corDF$taudensity <- fields::interp.surface(MASS::kde2d(corDF$Conceptualtau, corDF$Spatialtau), corDF[,c("Conceptualtau", "Spatialtau")]) #bivariate point density
uppertquartiles <- c(quantile(corDF$Conceptualtau, probs=c(.25, .75))[2], quantile(corDF$Spatialtau, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptualtau, na.rm = T), 1.5 * IQR(corDF$Spatialtau, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits


tauCor <-  "paste(r[tau], \" = .43\",  ~~italic(p), \" < .001\")"
p4c <- ggplot(subset(corDF, Conceptualtau<=upperLimit & Spatialtau<=upperLimit), aes(Conceptualtau, Spatialtau)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(method='lm', color='black',  se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  #expand_limits(x = 0, y = 0) +
  xlab(expression("Conceptual "*tau))+
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  ylab(expression("Spatial "*tau)) +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  #annotate("text", x = 0.1, y = 0.16, label = tauCor, parse=TRUE, size=4,  family="sans") +
  theme(text = element_text(size=16,  family="sans"))+
  theme(title = element_text(family = 'sans'),  legend.background = element_blank(), legend.position='right')
leg <- get_legend(p4c) #extract legend
p4c <- p4c + theme(legend.position = 'none')
p4c<- ggExtra::ggMarginal(p4c, type = "boxplot", fill='transparent', size=10)
p4c

#ggsave(filename = 'plots/tau.pdf', p2c, height =3, width = 3, units = "in")

#parameterPlots <- plot_grid(p4a, p4b, p4c, leg, nrow = 1, rel_widths = c(1,1,1,.4))
parameterPlots <- cowplot::plot_grid(p4a, p4b, p4c,leg, nrow = 1, rel_widths = c(1,1,1,.5))
#ggsave('plots/GPUCBparameters.pdf', parameterPlots, width = 9, height = 3, units='in')



###########################################################################################################################
#Put it together
###########################################################################################################################
TopRow <- cowplot::plot_grid(p1,p2, nrow =1, labels = 'auto')
pModel <- cowplot::plot_grid(TopRow, p3, parameterPlots, ncol=1, labels = c("", "c", "d"))
pModel

ggsave('plots/exp3ModelResults.pdf',pModel, width = 10, height = 8, unit='in', useDingbats=F)


###########################################################################################################################
#Parameter Correlation - BMT-UCB
###########################################################################################################################
#TODO: Update this properly

k<- 'BMT'
a<- "UCB"
conceptualDF<- subset(paramEstimates, kernel==k & acq==a & context=="Conceptual")
conceptualParams <- ddply(conceptualDF, ~participant+environment+contextOrder, plyr::summarize, ConceptualkError=mean(kError), Conceptualbeta = mean(beta), Conceptualtau = mean(tau))

gridDF<- subset(paramEstimates, kernel==k & acq==a & context == "Spatial")
gridParams <- ddply(gridDF, ~participant+environment+contextOrder, plyr::summarize, SpatialkError=mean(kError), Spatialbeta = mean(beta), Spatialtau = mean(tau))

corDF <- merge(conceptualParams, gridParams, by=c("participant", "environment", "contextOrder"))
corDF$environment <- factor(corDF$environment, levels=c("Rough", "Smooth"))

corTestPretty(corDF$SpatialkError, corDF$ConceptualkError, method='kendall')#correlation test
ranktestPretty(corDF$SpatialkError, corDF$ConceptualkError, paired=T) #$Z=-4.6$, $p<.001$, $r=-.41$, $BF=undefined$

uppertquartiles <- c(quantile(corDF$SpatialkError, probs=c(.25, .75))[2], quantile(corDF$ConceptualkError, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$SpatialkError, na.rm = T), 1.5 * IQR(corDF$ConceptualkError, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits

kCor <-  "paste(r[tau], \" = .18\",  ~~italic(p), \" = .003\")"
p3a <- ggplot(corDF, aes( ConceptualkError, SpatialkError )) +
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  xlab("Conceptual kError")+
  ylab("Spatial kError") +
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  annotate("text", x = 3, y =6, label = kCor, parse=TRUE, size=6,  family="sans") +
  theme_classic()+
  #ggtitle('BMT-UCB Parameters')+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18),legend.background = element_blank(), legend.position='none')
p3a<- ggExtra::ggMarginal(p3a, type = "boxplot", fill='transparent', size=10)
p3a

#beta

corTestPretty(corDF$Spatialbeta, corDF$Conceptualbeta, method='kendall')#correlation test
bCor <-  "paste(r[tau], \" = .16\",  ~~italic(p), \" = .006\")"

#ranktestPretty(corDF$Spatialbeta, corDF$Conceptualbeta, paired=T) #$Z=-5.6$, $p<.001$, $r=-.50$, $BFNA$

uppertquartiles <- c(quantile(corDF$Spatialbeta, probs=c(.25, .75))[2], quantile(corDF$Conceptualbeta, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Spatialbeta, na.rm = T), 1.5 * IQR(corDF$Conceptualbeta, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits
p3b <- ggplot(corDF, aes(Conceptualbeta, Spatialbeta)) +
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  #xlim(c(0,1))+
  #ylim(c(0,1))+
  xlab(expression("Conceptual "*beta))+
  ylab(expression("Spatial "*beta))+
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  theme_classic()+
  annotate("text", x = .15, y =.3, label = bCor, parse=TRUE, size=6,  family="sans") +
  #annotate("text", x = 1, y = 0.4, label = "r == 0.62 * ~~'p<.001'", parse=TRUE, size=6)+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18),legend.background = element_blank(), legend.position='none')
p3b<- ggExtra::ggMarginal(p3b, type = "boxplot", fill='transparent', size=10)
p3b

#tau
corTestPretty(corDF$Spatialtau, corDF$Conceptualtau, method='kendall')#correlation test
tCor <- "paste(r[tau], \" = .34\",  ~~italic(p), \" < .001\")"

ranktestPretty(corDF$Spatialtau, corDF$Conceptualtau, paired=T) 

uppertquartiles <- c(quantile(corDF$Spatialtau, probs=c(.25, .75))[2], quantile(corDF$Conceptualtau, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Spatialtau, na.rm = T), 1.5 * IQR(corDF$Conceptualtau, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits
p3c <- ggplot(corDF, aes(Conceptualtau, Spatialtau)) +
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  #xlim(c(0,1))+
  #ylim(c(0,1))+
  xlab(expression("Conceptual "*tau))+
  ylab(expression("Spatial "*tau))+
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  theme_classic()+
  annotate("text", x = .05, y =.12, label = tCor, parse=TRUE, size=6,  family="sans") +
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18),legend.background = element_blank(), legend.position='none')
p3c<- ggExtra::ggMarginal(p3c, type = "boxplot", fill='transparent', size=10)
p3c

p3 <- plot_grid(p3a,p3b, p3c, nrow=1)
p3

ggsave('plots/BMTUCBparameters.pdf', p3, width = 9, height = 3, units='in')




################################################################################################
#Graveyard
################################################################################################



###########################################################################################################################
#Parameter Correlation - Sim Kernel
###########################################################################################################################

k<- 'SimKernel'
a<- "UCB"
conceptualDF<- subset(paramEstimates, kernel==k & acq==a & context=="Conceptual")
conceptualParams <- ddply(conceptualDF, ~participant+environment+contextOrder, plyr::summarize, Conceptuallambda=mean(lambda), Conceptualbeta = mean(beta), Conceptualtau = mean(tau), Conceptualp = mean(p))

gridDF<- subset(paramEstimates, kernel==k & acq==a & context == "Spatial")
gridParams <- ddply(gridDF, ~participant+environment+contextOrder, plyr::summarize, Spatiallambda=mean(lambda), Spatialbeta = mean(beta), Spatialtau = mean(tau), Spatialp = mean(p))

corDF <- merge(conceptualParams, gridParams, by=c("participant", "environment", "contextOrder"))
corDF$environment <- factor(corDF$environment, levels=c("Rough", "Smooth"))

#Lambda correlation
corTestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda, method ='kendall') #$r_{\tau}=.13$, $p=.026$, $BF=1.3$
ranktestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda,  paired=T) #$Z=-1.8$, $p=.039$, $r=-.15$, $BF=.35$
#Beta
corTestPretty(conceptualParams$Conceptualbeta, gridParams$Spatialbeta, method ='kendall') #$r_{\tau}=.14$, $p=.021$, $BF=1.6$
ranktestPretty(conceptualParams$Conceptualbeta, gridParams$Spatialbeta, paired=T) # $Z=-5.5$, $p<.001$, $r=-.49$, $BF>100$
#tau
corTestPretty(conceptualParams$Conceptualtau, gridParams$Spatialtau, method ='kendall') #correlation test

#LAMBDA 
#Differences between conceptual and spatial
#ranktestPretty(conceptualParams$Conceptuallambda, gridParams$Spatiallambda, paired=T) #$Z=-1.7$, $p=.041$, $r=-.15$, $BF=.38$
#differences across environments
#ranktestPretty(c(subset(corDF, environment=="Rough")$Conceptuallambda, subset(corDF, environment=="Rough")$Spatiallambda), c(subset(corDF, environment=="Smooth")$Conceptuallambda, subset(corDF, environment=="Smooth")$Spatiallambda), paired=F) #$U=3229$, $p<.001$, $r_{\tau}=-.20$, $BF=7.2$

#Max axis value
uppertquartiles <- c(quantile(corDF$Conceptuallambda, probs=c(.25, .75))[2], quantile(corDF$Spatiallambda, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptuallambda, na.rm = T), 1.5 * IQR(corDF$Spatiallambda, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits
#Density for plotting
corDF$lambdadensity <- fields::interp.surface(MASS::kde2d(conceptualParams$Conceptuallambda, gridParams$Spatiallambda), corDF[,c("Conceptuallambda", "Spatiallambda")]) #bivariate point density

lambdaCor <- "paste(r[tau], \" = .13\",  ~~italic(p), \" = .026\")"
p2a <- ggplot(subset(corDF,Conceptuallambda <= upperLimit &  Spatiallambda<= upperLimit), aes(Conceptuallambda, Spatiallambda)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment
  #geom_smooth(method='lm', color='black', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  xlab(expression("Conceptual "*lambda))+
  ylab(expression("Spatial "*lambda)) +
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  annotate("text", x = 2, y = 3.5, label = lambdaCor, parse=TRUE, size=6,  family="sans") +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  theme(text = element_text(size=16,  family="sans"))+
  #ggtitle('Parameter correlations')+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18), legend.position='none', 
        legend.background = element_rect(fill='transparent'))
p2a <- ggExtra::ggMarginal(p2a, type = "boxplot", fill='transparent', size = 10, outlier.shape = NA) #add marginal boxplots
p2a
#ggsave(filename = 'plots/lambda.pdf', p2a, height =3, width = 3, units = "in")

#BETA
corTestPretty(corDF$Conceptualbeta, corDF$Spatialbeta, method = 'kendall') #correlation test
#ranktestPretty(corDF$Conceptualbeta, corDF$Spatialbeta, paired=T) 
#differences across environments
#ranktestPretty(c(subset(corDF, environment=="Rough")$Conceptualbeta, subset(corDF, environment=="Rough")$Spatialbeta), c(subset(corDF, environment=="Smooth")$Conceptualbeta, subset(corDF, environment=="Smooth")$Spatialbeta), paired=F) #$U=3780$, $p=.061$, $r_{\tau}=-.11$, $BF=.79$
#Spatial only
#ranktestPretty(subset(corDF, environment=="Rough")$Spatialbeta, subset(corDF, environment=="Smooth")$Spatialbeta, paired=F) #$U=737$, $p=.004$, $r_{\tau}=-.24$, $BF=2.4$

#Density and upper limits
corDF$betadensity <- fields::interp.surface(MASS::kde2d(corDF$Conceptualbeta, corDF$Spatialbeta), corDF[,c("Conceptualbeta", "Spatialbeta")]) #bivariate point density
uppertquartiles <- c(quantile(corDF$Conceptualbeta, probs=c(.25, .75))[2], quantile(corDF$Spatialbeta, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptualbeta, na.rm = T), 1.5 * IQR(corDF$Spatialbeta, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits


betaCor <- "paste(r[tau], \" = .14\",  ~~italic(p), \" = .021\")"
p2b <- ggplot(subset(corDF, Conceptualbeta<=upperLimit & Spatialbeta<=upperLimit), aes(Conceptualbeta, Spatialbeta)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(method='lm',color='black', se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  expand_limits(x = 0, y = 0) +
  scale_x_continuous(limits=c(0,upperLimit), breaks= scales::pretty_breaks(n = 5)) +
  scale_y_continuous(limits=c(0,upperLimit), breaks= scales::pretty_breaks(n = 5)) +
  xlab(expression("Conceptual "*beta))+
  ylab(expression("Spatial "*beta)) +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  annotate("text", x = 0.15, y = 0.3, label =betaCor, parse=TRUE, size=6,  family="sans")+
  theme(text = element_text(size=16,  family="sans"))+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18), legend.position="None")
p2b <- ggExtra::ggMarginal(p2b, type = "boxplot", fill='transparent', size=10)
p2b

#ggsave(filename = 'plots/beta.pdf', p2b, height =3, width = 3, units = "in")

#TAU
corTestPretty(corDF$Conceptualtau, corDF$Spatialtau, method = 'kendall') 
ttestPretty(corDF$Conceptualtau, corDF$Spatialtau, var.equal = TRUE, paired=T) #$t(94)=1.1$, $p=.265$, $d=0.2$, $BF=.21$

#Wilcoxon signed rank test
ranktestPretty(corDF$Conceptualtau, corDF$Spatialtau, paired=T) #$Z=-6.3$, $p<.001$, $r=-.55$, $BFNA$

#Density and upper limits
corDF$taudensity <- fields::interp.surface(MASS::kde2d(corDF$Conceptualtau, corDF$Spatialtau), corDF[,c("Conceptualtau", "Spatialtau")]) #bivariate point density
uppertquartiles <- c(quantile(corDF$Conceptualtau, probs=c(.25, .75))[2], quantile(corDF$Spatialtau, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptualtau, na.rm = T), 1.5 * IQR(corDF$Spatialtau, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits


tauCor <-  "paste(r[tau], \" = .41\",  ~~italic(p), \" < .001\")"
p2c <- ggplot(subset(corDF, Conceptualtau<=upperLimit & Spatialtau<=upperLimit), aes(Conceptualtau, Spatialtau)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(method='lm', color='black',  se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  #expand_limits(x = 0, y = 0) +
  xlab(expression("Conceptual "*tau))+
  scale_x_continuous(limits=c(0,upperLimit)) +
  scale_y_continuous(limits=c(0,upperLimit)) +
  ylab(expression("Spatial "*tau)) +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  annotate("text", x = 0.07, y = 0.17, label = tauCor, parse=TRUE, size=6,  family="sans") +
  theme(text = element_text(size=16,  family="sans"))+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18),legend.background = element_blank(), legend.position='none')
p2c<- ggExtra::ggMarginal(p2c, type = "boxplot", fill='transparent', size=10)
p2c


#Minkowwski P
corTestPretty(corDF$Conceptualp, corDF$Spatialp, method = 'kendall') #correlation test $r_{\tau}=-.02$, $p=.684$, $BF=.12$
ranktestPretty(corDF$Conceptualp, corDF$Spatialp, paired=T) #$Z=-2.5$, $p=.006$, $r=-.22$, $BF=2.5$

#Density and upper limits
corDF$taudensity <- fields::interp.surface(MASS::kde2d(corDF$Conceptualp, corDF$Spatialp), corDF[,c("Conceptualp", "Spatialp")]) #bivariate point density
uppertquartiles <- c(quantile(corDF$Conceptualp, probs=c(.25, .75))[2], quantile(corDF$Spatialp, probs=c(.25, .75))[2]) #upper quartiles
H <- c(1.5 * IQR(corDF$Conceptualp, na.rm = T), 1.5 * IQR(corDF$Spatialp, na.rm = T))
upperLimit <- max(uppertquartiles + H) #use the larger 1.5 * IQR from the upper quartile to set axis limits


pCor <-  "paste(r[tau], \" = -.02\",  ~~italic(p), \" = .684\")"
p2d <- ggplot(subset(corDF, Conceptualp<=upperLimit & Spatialp<=upperLimit), aes(Conceptualp, Spatialp)) +
  #geom_point(aes(color=contextOrder, shape=contextOrder), size =3, alpha=0.7)+ #task order
  geom_abline(slope = 1, intercept=0, color = 'black', linetype = 'dashed')+
  geom_point(aes(color=environment, shape=environment), size =3, alpha=0.9)+ #environment order
  #geom_smooth(aes(group=contextOrder, color = contextOrder), method='lm', se=FALSE, linetype=2, fullrange=TRUE)+
  #geom_smooth(method='lm', color='black',  se=FALSE, linetype=2, fullrange=TRUE)+
  #scale_fill_gradient(low = "#0091ff", high = "#f0650e") +
  #scale_alpha(range = c(.4, 1)) + guides(alpha="none", fill="none") +
  #expand_limits(x = 0, y = 0) +
  xlab(expression("Conceptual "*p))+
  scale_x_continuous(limits=c(0,2)) +
  scale_y_continuous(limits=c(0,2)) +
  ylab(expression("Spatial "*p)) +
  theme_classic()+
  scale_color_manual(name="", values=c("#24325FFF", '#B7E4F9FF'))+ #environment
  scale_shape_manual(name="", values= c(17,16))+
  #scale_color_brewer(palette = "Dark2", name = "", direction = -1) + #task order
  #scale_shape_manual(name="", values= c(16, 17))+
  annotate("text", x = 1, y = 0.1, label = pCor, parse=TRUE, size=6,  family="sans") +
  theme(text = element_text(size=16,  family="sans"))+
  theme(title = element_text(family = 'sans'),  axis.title=element_text(size=18),legend.background = element_blank(), legend.position='none')
p2d<- ggExtra::ggMarginal(p2d, type = "boxplot", fill='transparent', size=10)
p2d
#ggsave(filename = 'plots/tau.pdf', p2c, height =3, width = 3, units = "in")

parameterPlots <- plot_grid(p2a, p2b, p2d, p2c, labels = c('d', '', ''), nrow = 1)
ggsave('plots/SimKernelUCBparameters.pdf', parameterPlots, width = 12, height = 3, units='in')

#Boxplot of model comparison

se<-function(x){sd(x)/sqrt(length(x))}

mtmDF <- ddply(modelFit, ~kernel+acq+context, summarise, newR2 =mean(R2), se=se(R2))
boxplotDF <- ddply(plotDF, ~kernel+acq+context, summarise,d_ymin = max(min(R2), quantile(R2, 0.25) - 1.5 * IQR(R2)), d_ymax = min(max(R2), quantile(R2, 0.75) + 1.5 * IQR(R2)),
                   d_lower = quantile(R2, 0.25),  d_middle = median(R2), d_upper = quantile(R2, 0.75),
                   mu=mean(R2))

p1 <- ggplot(boxplotDF) +
  #Add connecting line
  geom_line(data=plotDF, aes(x = as.numeric(kernel)+.2,  y = R2,  group=participant), color = 'black', alpha = 0.2)+
  #stat_summary(fun.y = mean, geom = "bar", position = "dodge", color='black') + 
  geom_boxplot(aes(x =as.numeric(kernel)-0.2, ymin = d_lower, ymax = d_upper, lower = d_lower, middle = d_middle, upper = d_upper, width = 2 * 0.2, fill = kernel), stat = "identity", color='black') +
  #whiskers
  geom_segment(aes(x = as.numeric(kernel), y = d_ymin, xend = as.numeric(kernel), yend = d_ymax)) +
  geom_segment(aes(x = as.numeric(kernel) - 0.1,  y = d_ymax - 0.0025, xend = as.numeric(kernel),  yend = d_ymax -0.0025)) + #top
  geom_segment(aes(x = as.numeric(kernel) - 0.1, y = d_ymin +0.0025, xend = as.numeric(kernel), yend = d_ymin + 0.0025)) + #bottom
  geom_point(aes(x = as.numeric(kernel)-0.2, y = mu), size = 3, shape=23, fill='white') +
  #Add individual data points
  geom_jitter(data=plotDF, aes(x = as.numeric(kernel)+.2,  y = R2,  color = kernel, alpha=bestFit), width = 0.2 - 0.25 * 0.2, height = 0)+
  facet_grid(~context)+
  #geom_jitter(data = mainTextModels, aes(x=acq, y = R2, fill= kernel),  color='grey', size = 1, shape=21, alpha=0.2, position=position_jitterdodge(dodge.width=0.9, jitter.width = 0.2))+
  #geom_errorbar(aes(ymin=newR2 - se, ymax=newR2 + se),color='black', width = .4, position=position_dodge((width=0.9))) +
  scale_fill_manual(values = c("#F0E442", "#E69F00", "#009E73"),name='')+
  scale_color_manual(values = c("#F0E442", "#E69F00", "#009E73"),name='')+
  #scale_fill_manual(values = c("#56B4E9", "#E69F00" ), name="") +
  #scale_color_manual(values = c("#56B4E9", "#E69F00" ), name="") +
  ylab("Predictive Accuracy")+ 
  xlab('Task')+
  #coord_cartesian(ylim=c(-0.22, 0.8))+
  theme_classic()+
  theme(text = element_text(size=12,  family="sans"),
        strip.background=element_blank(),
        legend.key=element_rect(color=NA),
        panel.spacing.x=unit(0.2, "lines"),
        panel.spacing.y=unit(1, "lines"),
        plot.margin = unit(c(0, 0, 0, 0), "cm"),
        #legend.position=c(1,1),
        legend.position='right',
        legend.justification = c(1,1))+
  guides(color=FALSE, shape=FALSE)
p1



###########################################################################################################################
#Performance correlation
###########################################################################################################################
#Conceptual task
conceptualTask <- subset(modelFit, context =="Conceptual")
for (model in unique(conceptualTask$kernel)){
  cat(model)
  modelSub<- subset(conceptualTask, kernel==model)
  print(cor.test(modelSub$R2, modelSub$meanScore))
}

#Spatial task

spatialTask <- subset(modelFit, context =="Spatial")
for (model in unique(spatialTask$kernel)){
  cat(model)
  modelSub<- subset(spatialTask, kernel==model)
  print(cor.test(modelSub$R2, modelSub$meanScore))
}


ggplot(modelFit, aes(x=meanScore, y=R2, color=kernel, fill=kernel))+
  #geom_jitter(alpha=0.4)+
  stat_smooth(method='lm', alpha = 0.1, fullrange=TRUE) +
  geom_point(alpha=0.4)+
  
  facet_grid(~context) +
  #geom_rug(alpha=0.5)+
  theme_classic()+
  scale_color_brewer(palette = 'Dark2')+
  scale_fill_brewer(palette='Dark2')+
  theme(text = element_text(size=16,  family="sans"), strip.background=element_blank(), legend.key=element_rect(color=NA), legend.position="bottom")


###########################################################################################################################
#Distance of jump to log loss of choice
###########################################################################################################################
fullDF <- merge(data,choicePredictions,by.x=c("id", "context", "round", "trial", "environment"), by.y=c("participant", "context", "round", "trial", "environment"))

#scatter plot of reward and distance
meltedDF <- melt(fullDF, id.vars=c("id", "context", "environment", "nLL", "round", "trial","kernel", "acq", 'contextOrder'), measure.vars = c("distance"))
levels(meltedDF$variable) <- c("Spatial Distance", "Conceptual Distance")
levels(meltedDF$kernel)<- c("BMT", "Conceptual GP", "Spatial GP")
meltedDF$contextOrder <- factor(meltedDF$contextOrder) 
levels(meltedDF$contextOrder) <- c("Spatial First", "Conceptual First")

p5 <- ggplot(na.omit(fullDF), aes(x=distance, y = nLL, color = kernel, fill=kernel, linetype = environment)) +
  #geom_count(alpha=0.2, show.legend = F, position = position_dodge(width=0.1))+
  #scale_size_area(max_size = 5)+
  #geom_jitter(alpha=0.05, size=0.5)+
  stat_summary(fun.y = mean, geom = 'line', size = 1)+
  stat_summary(fun.data = mean_se, geom = 'ribbon', alpha = 0.2, color=NA) +
  theme_classic() +
  facet_grid(environment~ context)+
  geom_hline(yintercept = -log(1/25), color='black', linetype = 'dashed')+
  #ylab('Previous Reward Value')+
  xlab('Manhattan Distance')+
  #ylim(c(0,50))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))+
  scale_color_brewer(palette = 'Dark2', name="Model")+
  scale_fill_brewer( palette = 'Dark2', name="Model")+
  theme(legend.position='bottom', strip.background=element_blank(), legend.key=element_rect(color=NA),text = element_text(size=16,  family="sans"))
p5

meltedDF$choiceType <-ifelse(meltedDF$value==0, "Stay", ifelse(meltedDF$value %in% c(sqrt(1), sqrt(2)), "Near", "Far"))
meltedDF$R2  <- 1 - (meltedDF$nLL/-log(1/64)) 
meltedDF$choiceType <- factor(meltedDF$choiceType, levels=c("Stay", "Near", "Far"))
#meltedDF$kernel <- factor(meltedDF$kernel, levels = c("Conceptual GP", "Spatial GP", "BMT"))
p2 <- ggplot(meltedDF, aes(x=choiceType, y = nLL, fill=kernel))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", color='black') + 
  stat_summary(fun.data = mean_se, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2 ) +
  facet_grid(context~contextOrder ) +
  scale_fill_brewer(palette = "Dark2", name = "") +
  theme_classic()+
  geom_hline(yintercept = -log(1/64), color='black', linetype = 'dashed')+
  #scale_fill_rickandmorty()+
  theme(legend.position= 'bottom', strip.background=element_blank(), legend.key=element_rect(color=NA))+
  #scale_y_continuous(breaks = seq(0, 1, len = 6))+
  #ylab("Predictive accuracy") +
  ylab('Log Loss')+
  xlab("Choice Type")+ 
  #ggtitle("Unique and repeat clicks (per round)") +
  theme(text = element_text(size=16,  family="sans"))
p2

ggsave(filename = "plots/LogLossbyChoice.pdf", plot = p2, height =6, width = 7, units = "in") 